### PR TITLE
[non breaking change] flag to not truncate in parser

### PR DESCRIPTION
**Pull request by nichoth**

### CODE REVIEW

**Comment by bendrucker** [comment]
Can you explain the use case for this?

**Comment by nichoth** [comment]
Yes, I want to parse out any thing that is not a digit, but show the input as invalid if it is greater than 10 digits. 

Not to get too in depth, but if I am typing in a phone number, and I accidentally enter two keys instead of 1, then when I am done typing I look up and see that the field is valid b/c it has been truncated, I would move on with the form. But if I enter too many digits then see that the UI says it is invalid I would correct it.

**Comment by nichoth** [comment]
Actually, it looks like I need to patch the validator too so it check the length. It's ok if you don't want to merge this, I can keep using my fork :)

**Comment by bendrucker** [comment]
Understood. Go ahead and use a fork, I think truncation is a pretty common form pattern and I'd rather stick with something designed for that.

**Pull request closed without merging**
